---
abstract: 'A collection of debugging functions'
author:
  - 'Grant Street Group <developers@grantstreet.com>'
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
  overload: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBG
no_index: {}
requires:
  B: '0'
  B::Deparse: '0'
  Class::MOP: '0'
  Data::Dumper: '0'
  DateTime: '0'
  Devel::Size: '0'
  Exporter: '0'
  File::Spec: '0'
  FileHandle: '0'
  List::MoreUtils: '0'
  Perl::Tidy: '0'
  Scalar::Util: '0'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
version: '0.001'
